### ISSUE TITLE
array_key_exists on object

### ISSUE THREAD

**Issue by janvernieuwe** [AlexaCRM/dynamics-webapi-toolkit#24]
**Describe the bug**
array_key_exists is used on an object

**To Reproduce**
Use retrieveQueryViaAttribute

**Expected behavior**
No deprecation errors on PHP 7.4

**Additional context**
```
{
    "code": 500,
    "message": "array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead",
    "trace": [
        "#0 [internal function]: PHPUnit\\Util\\ErrorHandler->__invoke()",
        "#1 vendor\/alexacrm\/dynamics-webapi-toolkit\/src\/WebAPI\/Client.php(473): array_key_exists()",
        "#2 vendor\/alexacrm\/dynamics-webapi-toolkit\/src\/WebAPI\/Client.php(273): AlexaCRM\\WebAPI\\Client->retrieveViaQueryByAttribute()",
        ...
        "#24 {main}"
    ]
}
```

**Comment by janvernieuwe** [comment]
It would also be nice to have versioned releases
